const selections = {
    gender      : ['M','F','NA'],
    education   : [ 'Post-laurea' , 'Laurea' , 'Scuola superiore' , 'Altro' , 'Nessuno' ],
    industry    : [ 
        "Agenzie di ricerca personale / Staffing / Agenzie per l'impiego",
        "Agricoltura / Pesca",
        "Amministrazione e settore pubblico",
        "Assicurazioni",
        "Automotive",
        "Broadcasting / Musica / Produzione cinematografica",
        "Business services",
        "Commercio al dettaglio",
        "Commercio all'ingrosso / Import-Export",
        "Edilizia",
        "Energia",
        "Healthcare",
        "Hotels e ospitalità alberghiera",
        "Industria delle biotecnologie e farmaceutica",
        "Informatica / Telecomunicazioni",
        "Istruzione / Formazione",
        "Personal Care / Cosmetica",
        "Pubblicità / Public Relations",
        "Ristorazione / Food Services",
        "Servizi alla persona e alla famiglia",
        "Servizi e affari legali",
        "Settore immobiliare e amministazione di immobili",
        "Sport ",
        "Tecnologia",
        "Trasporto / Magazzinaggio materiali",
        "Altro",
        "Nessuno"
    ],
    function    : [ 
        "Acquisti / Logistica / Trasporti",
        "Amministrazione / Segreteria",
        "Commerciale / Business Development",
        "Contabilità / Finanza",
        "Creativo / Designer",
        "Edilizia e Professioni specialistiche",
        "Engineering",
        "Formazione / Istruzione",
        "Giornalisti / Redattori / Traduttori",
        "Informatica / Telecomunicazioni",
        "Legale",
        "Marketing / Comunicazione",
        "Personale medico e infermieristico",
        "Produzione / Operations",
        "Qualità / Sicurezza / Ambiente",
        "Ricerca e Sviluppo ",
        "Risorse Umane",
        "Ristorazione / Ospitalità alberghiera / Turismo",
        "Servizi di protezione / Vigilanza",
        "Supporto al cliente / Client service",
        "Top Strategic Management",
        "Altro ",
        "Nessuno" 
    ],
    role        : [ 
        "Consulente",
        "Educatore / Insegnante",
        "Impiegato ",
        "Imprenditore",
        "Libero professionista",
        "Manager",
        "Quadro ",
        "Ricercatore",
        "Studente",
        "Venditore",
        "Altro ",
        "Nessuno"
     ]
}


export default selections